social_auth_discord.settings:
  type: config_object
  label: 'Social Auth Discord settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Scopes to make API calls'
    api_calls:
      type: string
      label: 'API calls which will retrieve data'
